services:
  api:
    build:
      context: ./TASKe/TASKe
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  frontend:
    build:
      context: ./task-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  sql_data:
